- name: Installing dependencies
  apt:
    pkg: "{{ docker_deps }}"
    state: present
    update_cache: no
    install_recommends: no

- name: Adding repository key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id.lower() }}/gpg
    id: 0EBFCD88

- name: Adding repository
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_lsb.id.lower() }}
      {{ ansible_lsb.codename }}
      stable
  notify: update apt caches

- meta: flush_handlers

- name: Installing docker
  apt:
    pkg: docker-ce
    update_cache: no
    install_recommends: yes
  notify: restart docker

- name: Installing docker-compose
  when: docker_compose_enabled
  package:
    name: docker-compose
