- name: include distro vars
  include_vars: '{{ vars_item }}'
  with_first_found:
    - "{{ ansible_lsb.id }}.{{ ansible_lsb.release }}.yml"
    - "{{ ansible_lsb.id }}.yml"
    - "default.yml"
  loop_control:
    loop_var: vars_item

- name: include distro installer
  include_tasks: "{{ distro_installer }}"
  with_first_found:
    - "install/{{ ansible_lsb.id }}.{{ ansible_lsb.release }}.yml"
    - "install/{{ ansible_lsb.id }}.yml"
    - "install/default.yml"
  loop_control:
    loop_var: distro_installer

- name: include distro configurator
  include_tasks: "{{ distro_configurator }}"
  with_first_found:
    - "configure/{{ ansible_lsb.id }}.{{ ansible_lsb.release }}.yml"
    - "configure/{{ ansible_lsb.id }}.yml"
    - "configure/default.yml"
  loop_control:
    loop_var: distro_configurator
